/**
 * Base de datos de productos de Panadería El Nuevo Milenio
 * Mapeo directo a las fotos reales de productos y categorías
 * NOTA: Para actualizar el número de WhatsApp o datos del negocio, edita BAKERY_CONFIG al final de este archivo.
 */
const BAKERY_PRODUCTS = [
  {
    id: "pan-01",
    name: "Pan Casero Dorado Tradicional",
    category: "panaderia",
    categoryName: "Panadería Tradicional",
    price: 1500,
    priceFormatted: "$1.500",
    image: "pan-casero-dorado.jpeg",
    badge: "Más Vendido 🔥",
    badgeType: "hot",
    description: "Pan artesanal tradicional horneado diariamente. Corteza dorada y crujiente con miga esponjosa y aroma irresistible. Perfecto para acompañar con café, chocolate o queso.",
    portions: "1 Unidad grande",
    rating: 4.9,
    reviewsCount: 48,
    isFreshToday: true,
    tags: ["Pan", "Desayuno", "Artesanal", "Recién Horneado"]
  },
  {
    id: "pan-02",
    name: "Paquete de Pan de Queso / Especial x 5",
    category: "panaderia",
    categoryName: "Panadería Tradicional",
    price: 7500,
    priceFormatted: "$7.500",
    image: "pan-queso-paquete.jpeg",
    badge: "Horneado Hoy 🥖",
    badgeType: "fresh",
    description: "Paquete de 5 unidades de pan con suave queso campesino incorporado. Textura esponjosa, sabor balanceado y sellado para mantener máxima frescura.",
    portions: "Paquete de 5 unidades",
    rating: 5.0,
    reviewsCount: 62,
    isFreshToday: true,
    tags: ["Pan de Queso", "Paquete", "Familiar", "Desayuno"]
  },
  {
    id: "pan-03",
    name: "Surtido Panes Especiales (Vitrina Milenio)",
    category: "panaderia",
    categoryName: "Panadería Tradicional",
    price: 12000,
    priceFormatted: "$12.000",
    image: "surtido-panes-especiales.jpeg",
    badge: "Variedad de la Casa ⭐",
    badgeType: "special",
    description: "Disfruta de la máxima variedad de nuestra vitrina: panes hojaldrados, panes con semillas de ajonjolí, trenzas dulces, roscas doradas y mogollas campesinas.",
    portions: "Surtido variado (8 unidades surtidas)",
    rating: 4.9,
    reviewsCount: 89,
    isFreshToday: true,
    tags: ["Surtido", "Vitrina", "Hojaldre", "Ajonjolí", "Trenza"]
  },
  {
    id: "galleta-01",
    name: "Galletas Artesanales Estrellitas & Corazones",
    category: "galletas",
    categoryName: "Galletas & Repostería",
    price: 3000,
    priceFormatted: "$3.000",
    image: "galletas-decoradas.jpeg",
    badge: "Favorito Niños 🍪",
    badgeType: "popular",
    description: "Crocantes galletas de mantequilla con formas de estrellas y corazones, decoradas con abundante lluvia de granillos de colores. Masa suave y deliciosa.",
    portions: "Porción de 4 galletas",
    rating: 4.8,
    reviewsCount: 54,
    isFreshToday: true,
    tags: ["Galletas", "Mantequilla", "Colores", "Merienda"]
  },
  {
    id: "galleta-02",
    name: "Polvorones Tradicionales de Fresa con Azúcar Rojo",
    category: "galletas",
    categoryName: "Galletas & Repostería",
    price: 2500,
    priceFormatted: "$2.500",
    image: "polvorones-rojos.jpeg",
    badge: "Tradición Milenio ❤️",
    badgeType: "heritage",
    description: "Los clásicos polvorones de la casa: masa suave y arenosa con toque de fresa, cubiertos con azúcar cristalizada color rubí que se deshace en el paladar.",
    portions: "Porción de 2 unidades",
    rating: 4.9,
    reviewsCount: 73,
    isFreshToday: true,
    tags: ["Polvorones", "Fresa", "Dulce", "Tradicional"]
  },
  {
    id: "galleta-03",
    name: "Galleta Chocochips Doble Chocolate",
    category: "galletas",
    categoryName: "Galletas & Repostería",
    price: 3500,
    priceFormatted: "$3.500",
    image: "galleta-chocochips.jpeg",
    badge: "Nueva 🍫",
    badgeType: "hot",
    description: "Galleta americana crocante por fuera y suave por dentro, cargada de chips de chocolate semiamargo y chocolate blanco. Irresistibles.",
    portions: "Porción de 3 galletas",
    rating: 4.8,
    reviewsCount: 30,
    isFreshToday: true,
    tags: ["Chocochips", "Americana", "Chocolate", "Snack"]
  },
  {
    id: "postre-01",
    name: "Torta Húmeda Chocolate Supremo con Cacao",
    category: "postres",
    categoryName: "Postres & Tortas",
    price: 48000,
    priceFormatted: "$48.000",
    image: "torta-chocolate-supremo.jpeg",
    badge: "Recomendado del Chef 🍫",
    badgeType: "special",
    description: "Tres pisos de bizcocho extra húmedo de chocolate puro de cacao, capas de crema de ganache suave y coronada con elegantes rulos de chocolate artesanal.",
    portions: "10 a 12 Porciones (1.2 Kg aprox.)",
    rating: 5.0,
    reviewsCount: 110,
    isFreshToday: true,
    tags: ["Chocolate", "Torta Húmeda", "Cacao", "Gourmet"]
  },
  {
    id: "postre-02",
    name: "Torta Frutal Milenium con Cubierta de Nueces",
    category: "postres",
    categoryName: "Postres & Tortas",
    price: 52000,
    priceFormatted: "$52.000",
    image: "combo-desayuno-caliente.jpeg",
    badge: "Frescura Total 🍓",
    badgeType: "fresh",
    description: "Torta fresca de vainilla y tres leches decorada con kiwi natural, duraznos en almíbar, fresas maduras, uvas y lateral crujiente con nueces picadas.",
    portions: "12 a 15 Porciones",
    rating: 4.9,
    reviewsCount: 67,
    isFreshToday: true,
    tags: ["Frutas", "Kiwi", "Fresas", "Nueces", "Frescura"]
  },
  {
    id: "postre-03",
    name: "Torta Festiva Celeste Drip con Fresas & Durazno",
    category: "postres",
    categoryName: "Postres & Tortas",
    price: 55000,
    priceFormatted: "$55.000",
    image: "torta-tematica.jpeg",
    badge: "Ideal Celebración 🎉",
    badgeType: "popular",
    description: "Delicada crema chantilly color azul cielo con líneas acanaladas, drip de chocolate semiamargo, frutas frescas y topper de Feliz Cumpleaños incluido.",
    portions: "12 a 15 Porciones",
    rating: 4.9,
    reviewsCount: 45,
    isFreshToday: true,
    tags: ["Cumpleaños", "Celeste", "Drip Chocolate", "Frutas"]
  },
  {
    id: "postre-04",
    name: "Torta Glaseada de Frutos Rojos & Merenguitos",
    category: "postres",
    categoryName: "Postres & Tortas",
    price: 46000,
    priceFormatted: "$46.000",
    image: "galletas-decoradas.jpeg",
    badge: "Especial de la Casa ✨",
    badgeType: "special",
    description: "Cobertura de mermelada y reducción artesanal de frutos rojos, fresas glaseadas enteras, centro de durazno y suaves merenguitos espolvoreados con canela.",
    portions: "10 a 12 Porciones",
    rating: 4.8,
    reviewsCount: 39,
    isFreshToday: true,
    tags: ["Frutos Rojos", "Merengue", "Fresas", "Dulce"]
  },
  {
    id: "torta-01",
    name: "Torta Especial Feliz Cumpleaños Mamita T.Q.M.",
    category: "tortas",
    categoryName: "Tortas para Celebrar",
    price: 45000,
    priceFormatted: "$45.000",
    image: "galleta-chocochips.jpeg",
    badge: "Personalizable 💖",
    badgeType: "popular",
    description: "Hermosa torta con cubierta roja brillante de fresa, borde festoneado de crema chantilly, fresas frescas en almíbar y mensaje personalizado a tu gusto.",
    portions: "12 Porciones",
    rating: 5.0,
    reviewsCount: 88,
    isFreshToday: true,
    tags: ["Cumpleaños", "Mamá", "Personalizado", "Fresas"]
  },
  {
    id: "torta-02",
    name: "Torta Artesanal de Fresa & Kiwi para Celebrar",
    category: "tortas",
    categoryName: "Tortas para Celebrar",
    price: 44000,
    priceFormatted: "$44.000",
    image: "polvorones-rojos.jpeg",
    badge: "Delicada & Frutal 🍰",
    badgeType: "fresh",
    description: "Bizcochuelo extra suave con relleno cremoso, cubierta de coulis de fresa, rodajas de kiwi fresco y dedicatoria personalizada incluida.",
    portions: "10 a 12 Porciones",
    rating: 4.8,
    reviewsCount: 42,
    isFreshToday: true,
    tags: ["Kiwi", "Fresa", "Celebración", "Personalizado"]
  },
  {
    id: "torta-03",
    name: "Torta Turquesa Tentación con Melocotón y Frutas",
    category: "tortas",
    categoryName: "Tortas para Celebrar",
    price: 50000,
    priceFormatted: "$50.000",
    image: "torta-frutos-rojos.jpeg",
    badge: "Edición Especial 🎂",
    badgeType: "special",
    description: "Hermosa presentación turquesa con corona de chocolate escurrido, uvas moradas seleccionadas, melocotón en almíbar y fresas.",
    portions: "12 Porciones",
    rating: 4.9,
    reviewsCount: 51,
    isFreshToday: true,
    tags: ["Turquesa", "Chocolate", "Frutas", "Fiesta"]
  },
  {
    id: "torta-tematica-01",
    name: "Torta Temática Personalizada TikTok",
    category: "tortas",
    categoryName: "Tortas para Celebrar",
    price: 65000,
    priceFormatted: "$65.000",
    image: "torta-tres-leches.jpeg",
    badge: "Temática Juvenil 📱",
    badgeType: "hot",
    description: "Torta cuadrada temática TikTok con audífonos 3D, autito de juguete, logotipos de TikTok comestibles y dedicatoria con nombre y edad del cumpleañero/a.",
    portions: "18 a 20 Porciones",
    rating: 5.0,
    reviewsCount: 36,
    isFreshToday: true,
    tags: ["TikTok", "Temática", "Juvenil", "Cumpleaños"]
  },
  {
    id: "torta-tematica-02",
    name: "Dúo de Tortas Unicornio Fantasía & Rosetones",
    category: "tortas",
    categoryName: "Tortas para Celebrar",
    price: 68000,
    priceFormatted: "$68.000",
    image: "mogolla-campesina.jpeg",
    badge: "Temática Infantil 🦄",
    badgeType: "popular",
    description: "Set de 2 tortas infantiles: Torta principal Unicornio con cono dorado, orejitas y rosetones pastel azul/rosa + Torta complementaria a juego.",
    portions: "20 a 24 Porciones (2 Tortas)",
    rating: 5.0,
    reviewsCount: 49,
    isFreshToday: true,
    tags: ["Unicornio", "Infantil", "Pastel", "Dúo Tortas"]
  },
  {
    id: "combo-01",
    name: "Combo Desayuno Milenio Tradicional",
    category: "combos",
    categoryName: "Combos & Promociones",
    price: 8500,
    priceFormatted: "$8.500",
    image: "pan-casero-dorado.jpeg",
    badge: "Ahorro del Día ☕",
    badgeType: "hot",
    description: "Incluye: 2 Panes caseros calientes dorados + 1 Café con Leche o Chocolate Caliente Espumoso + 2 Galletas decoradas.",
    portions: "Para 1 o 2 personas",
    rating: 4.9,
    reviewsCount: 95,
    isFreshToday: true,
    tags: ["Combo", "Desayuno", "Café", "Pan Caliente"]
  },
  {
    id: "combo-02",
    name: "Combo Merienda Dulce de la Tarde",
    category: "combos",
    categoryName: "Combos & Promociones",
    price: 11000,
    priceFormatted: "$11.000",
    image: "combo-tarde-dulce.jpeg",
    badge: "Favorito Tarde 🍰",
    badgeType: "popular",
    description: "Incluye: 1 Porción generosa de Torta de Chocolate Supremo o Frutos Rojos + 1 Polvorón tradicional de fresa + 1 Bebida fría o caliente.",
    portions: "Para 1 persona",
    rating: 5.0,
    reviewsCount: 81,
    isFreshToday: true,
    tags: ["Combo", "Torta", "Polvorón", "Merienda"]
  }
];

// ============================================================
// CONFIGURACIÓN GENERAL — Editar con los datos reales del negocio
// ============================================================
const BAKERY_CONFIG = {
  name: "Panadería y Repostería El Nuevo Milenio",
  slogan: "El auténtico sabor tradicional y los postres más deliciosos, horneados con amor",
  // ⚠️ REEMPLAZAR con el número real de WhatsApp del negocio (formato: 57XXXXXXXXXX)
  phone: "+57 300 123 4567",
  whatsappNumber: "573001234567",
  // ⚠️ REEMPLAZAR con la dirección real de la panadería
  address: "Calle Principal # 12-34, Barrio Central",
  city: "Colombia",
  hours: "Lunes a Domingo: 6:00 AM - 9:30 PM",
  freshSchedule: "Horneadas calientes a las: 6:30 AM, 11:30 AM y 4:30 PM",
  currency: "COP",
  currencySymbol: "$",
  deliveryCost: 4000
};
